version: "3"

services:
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    ports:
      - '80:8079'
    environment:
      - reschedule=on-node-failure
    deploy:
      replicas: 3
    networks:
      - new_network_name

  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    environment:
      - reschedule=on-node-failure
    deploy:
      replicas: 3
    networks:
      - new_network_name

  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    deploy:
      replicas: 3
    networks:
      - new_network_name

  carts:
    image: weaveworksdemos/carts:0.4.8
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    deploy:
      replicas: 3
    networks:
      - new_network_name

  carts-db:
    image: mongo:3.4
    environment:
      - reschedule=on-node-failure
    deploy:
      replicas: 3
    networks:
      - new_network_name

  orders:
    image: weaveworksdemos/orders:0.4.7
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    deploy:
      replicas: 3
    networks:
      - new_network_name

  orders-db:
    image: mongo:3.4
    environment:
      - reschedule=on-node-failure
    deploy:
      replicas: 3
    networks:
      - new_network_name

  shipping:
    image: weaveworksdemos/shipping:0.4.8
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    deploy:
      replicas: 3
    networks:
      - new_network_name

  rabbitmq:
    image: rabbitmq:3.6.8
    environment:
      - reschedule=on-node-failure
    deploy:
      replicas: 3
    networks:
      - new_network_name

  payment:
    image: weaveworksdemos/payment:0.4.3
    environment:
      - reschedule=on-node-failure
    deploy:
      replicas: 3
    networks:
      - new_network_name

  user:
    image: weaveworksdemos/user:0.4.4
    environment:
      - MONGO_HOST=user-db:27017
      - reschedule=on-node-failure
    deploy:
      replicas: 3
    networks:
      - new_network_name

  user-db:
    image: weaveworksdemos/user-db:0.4.0
    environment:
      - reschedule=on-node-failure
    deploy:
      replicas: 3
    networks:
      - new_network_name

networks:
  new_network_name:
    driver: overlay

